[package]
name = "aoc_2019"
version = "0.1.0"
authors = ["Simon Berger <simon@siku2.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
clap = "2.33.0"
colored = "1.9"
pathfinding = "2.0.1"
