title: "Advent of Code 2019"
author: "Simon Berger"
description: "The story of my slow descent into madness"

collections:
  posts:
    permalink: /day/:i_day

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "puzzle-post"

theme: jekyll-theme-hacker
show_downloads: false
