title: "Advent of Code 2019"
description: "The story of my slow descent into madness"

collections:
  posts:
    permalink: /day/:i_day

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Simon Berger"

theme: jekyll-theme-hacker
show_downloads: false
